import { Stove } from "./StoveConcept/Stove/stove.js";
import { KitchenRanges } from "./StoveConcept/KitchenRanges/kitchen-ranges.js";
import { StoveBurner } from "./StoveConcept/StoveBurner/stove-burner.js";
import { StoveOven } from "./StoveConcept/StoveOven/stove-oven.js";
import { OvenGlass } from "./StoveConcept/StoveOven/OvenGlass/oven-glass.js";
import { TurnOnLamp } from "./StoveConcept/StoveOven/TurnOnLamp/turn-on-lamp.js";
import { OvenLamp } from "./StoveConcept/StoveOven/OvenLamp/oven-lamp.js";
import { Lighter } from "./StoveConcept/Lighter/lighter.js";
import { StovePanel } from "./StoveConcept/StovePanel/stove-panel.js";